/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class BRepAlgo_Cut extends BRepAlgo_BooleanOperation {
  private long swigCPtr;

  protected BRepAlgo_Cut(long cPtr, boolean cMemoryOwn) {
    super(OccJavaJNI.BRepAlgo_Cut_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BRepAlgo_Cut obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_BRepAlgo_Cut(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public BRepAlgo_Cut(TopoDS_Shape S1, TopoDS_Shape S2) {
    this(OccJavaJNI.new_BRepAlgo_Cut(TopoDS_Shape.getCPtr(S1), S1, TopoDS_Shape.getCPtr(S2), S2), true);
  }

}
