/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class BRepAlgo_BooleanOperation extends BRepBuilderAPI_MakeShape {
  private long swigCPtr;

  protected BRepAlgo_BooleanOperation(long cPtr, boolean cMemoryOwn) {
    super(OccJavaJNI.BRepAlgo_BooleanOperation_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BRepAlgo_BooleanOperation obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_BRepAlgo_BooleanOperation(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void Delete() {
    OccJavaJNI.BRepAlgo_BooleanOperation_Delete(swigCPtr, this);
  }

  public void performDS() {
    OccJavaJNI.BRepAlgo_BooleanOperation_performDS(swigCPtr, this);
  }

  public void perform(SWIGTYPE_p_TopAbs_State St1, SWIGTYPE_p_TopAbs_State St2) {
    OccJavaJNI.BRepAlgo_BooleanOperation_perform(swigCPtr, this, SWIGTYPE_p_TopAbs_State.getCPtr(St1), SWIGTYPE_p_TopAbs_State.getCPtr(St2));
  }

  public SWIGTYPE_p_Handle_TopOpeBRepBuild_HBuilder builder() {
    return new SWIGTYPE_p_Handle_TopOpeBRepBuild_HBuilder(OccJavaJNI.BRepAlgo_BooleanOperation_builder(swigCPtr, this), true);
  }

  public TopoDS_Shape shape1() {
    long cPtr = OccJavaJNI.BRepAlgo_BooleanOperation_shape1(swigCPtr, this);
    return (TopoDS_Shape)TopoDS_Shape.create(cPtr);
}

  public TopoDS_Shape Shape2() {
    long cPtr = OccJavaJNI.BRepAlgo_BooleanOperation_Shape2(swigCPtr, this);
    return (TopoDS_Shape)TopoDS_Shape.create(cPtr);
}

  public TopoDS_Shape[] modified(TopoDS_Shape S) {
	return TopoDS_Shape.cArrayWrap(OccJavaJNI.BRepAlgo_BooleanOperation_modified(swigCPtr, this, TopoDS_Shape.getCPtr(S), S));
}

  public boolean IsDeleted(TopoDS_Shape S) {
	return OccJavaJNI.BRepAlgo_BooleanOperation_IsDeleted(swigCPtr, this, TopoDS_Shape.getCPtr(S), S);
}

}
