/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class BRepOffsetAPI_ThruSections extends BRepBuilderAPI_MakeShape {
  private long swigCPtr;

  protected BRepOffsetAPI_ThruSections(long cPtr, boolean cMemoryOwn) {
    super(OccJavaJNI.BRepOffsetAPI_ThruSections_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BRepOffsetAPI_ThruSections obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_BRepOffsetAPI_ThruSections(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public BRepOffsetAPI_ThruSections(boolean isSolid, boolean ruled, double pres3d) {
    this(OccJavaJNI.new_BRepOffsetAPI_ThruSections__SWIG_0(isSolid, ruled, pres3d), true);
  }

  public BRepOffsetAPI_ThruSections(boolean isSolid, boolean ruled) {
    this(OccJavaJNI.new_BRepOffsetAPI_ThruSections__SWIG_1(isSolid, ruled), true);
  }

  public BRepOffsetAPI_ThruSections(boolean isSolid) {
    this(OccJavaJNI.new_BRepOffsetAPI_ThruSections__SWIG_2(isSolid), true);
  }

  public BRepOffsetAPI_ThruSections() {
    this(OccJavaJNI.new_BRepOffsetAPI_ThruSections__SWIG_3(), true);
  }

  public void addWire(TopoDS_Wire wire) {
    OccJavaJNI.BRepOffsetAPI_ThruSections_addWire(swigCPtr, this, TopoDS_Wire.getCPtr(wire), wire);
  }

  public void setParType(Approx_ParametrizationType ParType) {
    OccJavaJNI.BRepOffsetAPI_ThruSections_setParType(swigCPtr, this, ParType.swigValue());
  }

}
