/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class BRepOffsetAPI_MakePipeShell extends BRepPrimAPI_MakeSweep {
  private long swigCPtr;

  protected BRepOffsetAPI_MakePipeShell(long cPtr, boolean cMemoryOwn) {
    super(OccJavaJNI.BRepOffsetAPI_MakePipeShell_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BRepOffsetAPI_MakePipeShell obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_BRepOffsetAPI_MakePipeShell(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public BRepOffsetAPI_MakePipeShell(TopoDS_Wire Spine) {
    this(OccJavaJNI.new_BRepOffsetAPI_MakePipeShell(TopoDS_Wire.getCPtr(Spine), Spine), true);
  }

  public void SetMode(boolean IsFrenet) {
    OccJavaJNI.BRepOffsetAPI_MakePipeShell_SetMode__SWIG_0(swigCPtr, this, IsFrenet);
  }

  public void SetMode() {
    OccJavaJNI.BRepOffsetAPI_MakePipeShell_SetMode__SWIG_1(swigCPtr, this);
  }

  public void setDiscreteMode() {
    OccJavaJNI.BRepOffsetAPI_MakePipeShell_setDiscreteMode(swigCPtr, this);
  }

  public void setModeAx2(double[] Axe) {
    OccJavaJNI.BRepOffsetAPI_MakePipeShell_setModeAx2(swigCPtr, this, Axe);
  }

  public void setModeBiNormal(double[] BiNormal) {
    OccJavaJNI.BRepOffsetAPI_MakePipeShell_setModeBiNormal(swigCPtr, this, BiNormal);
  }

  public boolean SetMode(TopoDS_Shape SpineSupport) {
	return OccJavaJNI.BRepOffsetAPI_MakePipeShell_SetMode__SWIG_2(swigCPtr, this, TopoDS_Shape.getCPtr(SpineSupport), SpineSupport);
}

  public void SetMode(TopoDS_Wire AuxiliarySpine, boolean CurvilinearEquivalence, BRepFill_TypeOfContact KeepContact) {
    OccJavaJNI.BRepOffsetAPI_MakePipeShell_SetMode__SWIG_3(swigCPtr, this, TopoDS_Wire.getCPtr(AuxiliarySpine), AuxiliarySpine, CurvilinearEquivalence, KeepContact.swigValue());
  }

  public void SetMode(TopoDS_Wire AuxiliarySpine, boolean CurvilinearEquivalence) {
    OccJavaJNI.BRepOffsetAPI_MakePipeShell_SetMode__SWIG_4(swigCPtr, this, TopoDS_Wire.getCPtr(AuxiliarySpine), AuxiliarySpine, CurvilinearEquivalence);
  }

  public void add1(TopoDS_Shape Profile, boolean WithContact, boolean WithCorrection) {
    OccJavaJNI.BRepOffsetAPI_MakePipeShell_add1__SWIG_0(swigCPtr, this, TopoDS_Shape.getCPtr(Profile), Profile, WithContact, WithCorrection);
  }

  public void add1(TopoDS_Shape Profile, boolean WithContact) {
    OccJavaJNI.BRepOffsetAPI_MakePipeShell_add1__SWIG_1(swigCPtr, this, TopoDS_Shape.getCPtr(Profile), Profile, WithContact);
  }

  public void add1(TopoDS_Shape Profile) {
    OccJavaJNI.BRepOffsetAPI_MakePipeShell_add1__SWIG_2(swigCPtr, this, TopoDS_Shape.getCPtr(Profile), Profile);
  }

  public void add2(TopoDS_Shape Profile, TopoDS_Vertex Location, boolean WithContact, boolean WithCorrection) {
    OccJavaJNI.BRepOffsetAPI_MakePipeShell_add2__SWIG_0(swigCPtr, this, TopoDS_Shape.getCPtr(Profile), Profile, TopoDS_Vertex.getCPtr(Location), Location, WithContact, WithCorrection);
  }

  public void add2(TopoDS_Shape Profile, TopoDS_Vertex Location, boolean WithContact) {
    OccJavaJNI.BRepOffsetAPI_MakePipeShell_add2__SWIG_1(swigCPtr, this, TopoDS_Shape.getCPtr(Profile), Profile, TopoDS_Vertex.getCPtr(Location), Location, WithContact);
  }

  public void add2(TopoDS_Shape Profile, TopoDS_Vertex Location) {
    OccJavaJNI.BRepOffsetAPI_MakePipeShell_add2__SWIG_2(swigCPtr, this, TopoDS_Shape.getCPtr(Profile), Profile, TopoDS_Vertex.getCPtr(Location), Location);
  }

  public void Delete(TopoDS_Shape Profile) {
    OccJavaJNI.BRepOffsetAPI_MakePipeShell_Delete(swigCPtr, this, TopoDS_Shape.getCPtr(Profile), Profile);
  }

  public boolean isReady() {
	return OccJavaJNI.BRepOffsetAPI_MakePipeShell_isReady(swigCPtr, this);
}

  public BRepBuilderAPI_PipeError getStatus() {
    return BRepBuilderAPI_PipeError.swigToEnum(OccJavaJNI.BRepOffsetAPI_MakePipeShell_getStatus(swigCPtr, this));
  }

  public void setTolerance(double Tol3d, double BoundTol, double TolAngular) {
    OccJavaJNI.BRepOffsetAPI_MakePipeShell_setTolerance__SWIG_0(swigCPtr, this, Tol3d, BoundTol, TolAngular);
  }

  public void setTolerance(double Tol3d, double BoundTol) {
    OccJavaJNI.BRepOffsetAPI_MakePipeShell_setTolerance__SWIG_1(swigCPtr, this, Tol3d, BoundTol);
  }

  public void setTolerance(double Tol3d) {
    OccJavaJNI.BRepOffsetAPI_MakePipeShell_setTolerance__SWIG_2(swigCPtr, this, Tol3d);
  }

  public void setTolerance() {
    OccJavaJNI.BRepOffsetAPI_MakePipeShell_setTolerance__SWIG_3(swigCPtr, this);
  }

  public void setForceApproxC1(boolean ForceApproxC1) {
    OccJavaJNI.BRepOffsetAPI_MakePipeShell_setForceApproxC1(swigCPtr, this, ForceApproxC1);
  }

  public void setTransitionMode(BRepBuilderAPI_TransitionMode Mode) {
    OccJavaJNI.BRepOffsetAPI_MakePipeShell_setTransitionMode__SWIG_0(swigCPtr, this, Mode.swigValue());
  }

  public void setTransitionMode() {
    OccJavaJNI.BRepOffsetAPI_MakePipeShell_setTransitionMode__SWIG_1(swigCPtr, this);
  }

  public void simulate(int NumberOfSection, SWIGTYPE_p_TopTools_ListOfShape Result) {
    OccJavaJNI.BRepOffsetAPI_MakePipeShell_simulate(swigCPtr, this, NumberOfSection, SWIGTYPE_p_TopTools_ListOfShape.getCPtr(Result));
  }

  public void build() {
    OccJavaJNI.BRepOffsetAPI_MakePipeShell_build(swigCPtr, this);
  }

  public boolean makeSolid() {
	return OccJavaJNI.BRepOffsetAPI_MakePipeShell_makeSolid(swigCPtr, this);
}

  public TopoDS_Shape firstShape() {
    long cPtr = OccJavaJNI.BRepOffsetAPI_MakePipeShell_firstShape(swigCPtr, this);
    return (TopoDS_Shape)TopoDS_Shape.create(cPtr);
}

  public TopoDS_Shape lastShape() {
    long cPtr = OccJavaJNI.BRepOffsetAPI_MakePipeShell_lastShape(swigCPtr, this);
    return (TopoDS_Shape)TopoDS_Shape.create(cPtr);
}

  public TopoDS_Shape[] generated(TopoDS_Shape S) {
	return TopoDS_Shape.cArrayWrap(OccJavaJNI.BRepOffsetAPI_MakePipeShell_generated(swigCPtr, this, TopoDS_Shape.getCPtr(S), S));
}

}
