/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jcae.opencascade.jni;

public class GCPnts_AbscissaPoint {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected GCPnts_AbscissaPoint(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GCPnts_AbscissaPoint obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OccJavaJNI.delete_GCPnts_AbscissaPoint(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static double length(Adaptor3d_Curve C) {
    return OccJavaJNI.GCPnts_AbscissaPoint_length__SWIG_0(Adaptor3d_Curve.getCPtr(C), C);
  }

  public static double length(Adaptor3d_Curve C, double Tol) {
    return OccJavaJNI.GCPnts_AbscissaPoint_length__SWIG_1(Adaptor3d_Curve.getCPtr(C), C, Tol);
  }

  public static double length(Adaptor3d_Curve C, double U1, double U2) {
    return OccJavaJNI.GCPnts_AbscissaPoint_length__SWIG_2(Adaptor3d_Curve.getCPtr(C), C, U1, U2);
  }

  public static double length(Adaptor3d_Curve C, double U1, double U2, double Tol) {
    return OccJavaJNI.GCPnts_AbscissaPoint_length__SWIG_3(Adaptor3d_Curve.getCPtr(C), C, U1, U2, Tol);
  }

  public GCPnts_AbscissaPoint() {
    this(OccJavaJNI.new_GCPnts_AbscissaPoint__SWIG_0(), true);
  }

  public GCPnts_AbscissaPoint(Adaptor3d_Curve C, double Abscissa, double U0) {
    this(OccJavaJNI.new_GCPnts_AbscissaPoint__SWIG_1(Adaptor3d_Curve.getCPtr(C), C, Abscissa, U0), true);
  }

  public GCPnts_AbscissaPoint(double Tol, Adaptor3d_Curve C, double Abscissa, double U0) {
    this(OccJavaJNI.new_GCPnts_AbscissaPoint__SWIG_2(Tol, Adaptor3d_Curve.getCPtr(C), C, Abscissa, U0), true);
  }

  public boolean isDone() {
	return OccJavaJNI.GCPnts_AbscissaPoint_isDone(swigCPtr, this);
}

  public double parameter() {
    return OccJavaJNI.GCPnts_AbscissaPoint_parameter(swigCPtr, this);
  }

}
